#cloud-config
runcmd:
  - dnf config-manager --add-repo 'https://loopholelabs.github.io/linux-pvm-ci/alma/hetzner/repodata/linux-pvm-ci.repo'
  - dnf install -y kernel-6.7.12_pvm_host_alma_hetzner-1.x86_64
  - grubby --set-default /boot/vmlinuz-6.7.12-pvm-host-alma-hetzner
  - grubby --copy-default --args="pti=off nokaslr lapic=notscdeadline" --update-kernel /boot/vmlinuz-6.7.12-pvm-host-alma-hetzner
  - dracut --force --kver 6.7.12-pvm-host-alma-hetzner
  - reboot

write_files:
  - path: /etc/modprobe.d/kvm-intel-amd-blacklist.conf
    permissions: "0644"
    content: |
      blacklist kvm-intel
      blacklist kvm-amd
  - path: /etc/modules-load.d/kvm-pvm.conf
    permissions: "0644"
    content: |
      kvm-pvm

power_state:
  mode: reboot
  condition: True
